import = ["/home/pjhades/.config/alacritty/themes/themes/blood_moon.yaml"]

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.offset]
x = 0
y = 3

[window]
decorations = "full"
opacity = 0.95
